### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by co-dh** [ankurdave/color-identifiers-mode#34]
I noticed that typescript with react ( tsx) files are not supported. 
Can we support it? or even better, support all language automatically ?

**Comment by Hi-Angel** [comment]
I was thinking of it, theoretically it's possible to support all langs having set the `font-lock-variable-name-face`. But in practice I don't know how to check it. E.g. you can't check all currently set faces, because their current absence doesn't guarantee the future. Another way: modes have a list of faces, so you can check if it has `font-lock-variable-name-face`. Unfortunately the name of that list is completely arbitrary, e.g. in rust-mode it's `rust-mode-font-lock-keywords`.
