### ISSUE TITLE
Every single word in a JSX block is colored in js2-jsx-mode

### ISSUE THREAD

**Issue by thblt** [ankurdave/color-identifiers-mode#62]
The title says it all, really. JSX blocks are completely colorized, including regular HTML text.
![capture du 2018-12-09 16-40-38](https://user-images.githubusercontent.com/2453136/49699419-3b835700-fbd1-11e8-9db3-a9a7467f960d.png)

The same issue appears in `js-jsx-mode`

Thanks!

**Comment by Hi-Angel** [comment]
So, FYI, while working on [something else](https://github.com/ankurdave/color-identifiers-mode/pull/64), I took a short stub at it, and the reason you see this turned out to be [`nil` here](https://github.com/ankurdave/color-identifiers-mode/blob/4ba39f0274e1f85e50c956c507f942d950891a20/color-identifiers-mode.el#L224). The reason it's there in the first place is that documentation about variable `color-identifiers:modes-alist` says:

> If the list includes nil, unfontified words will be considered.

As result, every list for every major mode contain `nil` in particular.

Per my understanding, this cannot result in proper colorizing, what you see should in fact happen with every mode. Maybe @ankurdave could tell more about it…?

**Comment by Hi-Angel** [comment]
To be more specific about how `nil` is causing it: in the affected mode the `color-identifiers:scan-identifiers` function calls this part `(memq (get-text-property (point) 'face) identifier-faces)` for every word. And for every word `(get-text-property (point) 'face)` returns `nil`, which is stored as one of the faces for the mode, so the whole expression evaluates to `t`.

**Comment by Hi-Angel** [comment]
@thblt Yeah, and as a workaround, removing the nil should work.
